name: delta_markdown
version: 0.4.0

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  charcode: ^1.3.1
  collection: ^1.16.0
  flutter_quill: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  test: ^1.21.1
